version: "3.8"

services:
  # ------------------
  # Database Service
  # ------------------
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  # ------------------
  # Backend Service
  # ------------------
  backend-service:
    #image: bera1998/3-tire-end-to-end-backend-service
    build: ./backend
    container_name: backend-service
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
    ports:
      - "5000:5000"

  # ------------------
  # Frontend Service
  # ------------------
  frontend:
    image: bera1998/3-tire-end-to-end-frontend
    container_name: flower-frontend
    restart: always
    depends_on:
      - backend-service
    ports:
      - "8080:80"

